language: node_js

node_js:
  - "node"
  
install:
  - npm install --silent

cache:
  directories:
    - node_modules # NPM packages

jobs:
  include:
    - stage: "Tests"
      name: "Validator unit testing"
      script: npm run test:validation
      name: "Repository unit testing"
      script: npm run test:repository
      name: "Integration testing"
      script: npm run test:integration

services: mongodb
